name: Try build

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Try build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun --install --frozen-lockfile

      - name: Test build website
        run: bun run build
